export const mockPosts = [
  {
    id: "1",
    title: "Mock Post 1",
    description: "This is the content of mock post 1.",
    content: "This is the detailed content of mock post 1.",
    views: 100,
    comments: [{id: "1", content: "Great post!", author: "User1", date: "2023-10-01"}],
  },
  {
    id: "2",
    title: "Mock Post 2",
    description: "This is the content of mock post 1.",
    content: "This is the detailed content of mock post 1.",
    views: 100,
    comments: [{id: "2", content: "Great post!", author: "User2", date: "2023-10-01"}],
  },
  {
    id: "3",
    title: "Mock Post 3",
    description: "This is the content of mock post 1.",
    content: "This is the detailed content of mock post 1.",
    views: 100,
    comments: [{id: "4", content: "Great post!", author: "User1", date: "2023-10-01"}],
  },
  {
    id: "4",
    title: "Mock Post 4",
    description: "This is the content of mock post 1.",
    content: "This is the detailed content of mock post 1.",
    views: 100,
    comments: [{id: "3", content: "Great post!", author: "User1", date: "2023-10-01"}],
  },
  {
    id: "5",
    title: "Mock Post 5",
    description: "This is the content of mock post 1.",
    content: "This is the detailed content of mock post 1.",
    views: 100,
    comments: [{id: "7", content: "Great post!", author: "User1", date: "2023-10-01"}],
  },
  {
    id: "6",
    title: "Mock Post 6",
    description: "This is the content of mock post 1.",
    content: "This is the detailed content of mock post 1.",
    views: 100,
    comments: [{id: "5", content: "Great post!", author: "User1", date: "2023-10-01"}],
  },
  {
    id: "7",
    title: "Mock Post 7",
    description: "This is the content of mock post 1.",
    content: "This is the detailed content of mock post 1.",
    views: 100,
    comments: [{id: "3", content: "Great post!", author: "User1", date: "2023-10-01"}],
  },

]